### ISSUE TITLE
Paste stopped working (“CFPasteboardRef: Lock timeout”)

### ISSUE THREAD

**Issue by forthrin** [TermiT/Flycut#103]
After uninstalling FlyCut (simple Cmd+Delete in Applications), pasting from the clipboard stopped working on my Mac. Nothing is pasted, and the following line appears many time in syslog.

    Apr  5 **:**:** *** com.apple.WebKit.WebContent[6583] <Warning>: CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : Lock timeout

My immediate thought is that FlyCut has left behind some hook or process. I can see no running related process (using `ps -ef`). Rebooting temporarily solves the problem, but returns at some point.

**Comment by TermiT** [comment]
Sorry, but I don't see how FlyCut can do something like this.

**Comment by forthrin** [comment]
Do you have any knowledge of the `Pasteboard` class that could help understand what is going on?

**Comment by beane** [comment]
I'm having the same issue but I don't have fly cut. I think it's a Mac-specific thing, but I have no idea why it started.

**Comment by MarkJerde** [comment]
There are a lot more reports of this problem on various different application support forums now than when @forthrin posted it originally. I've only seen one mention of OS version, and that was 10.11.3. I'm guessing everyone having this problem is on El Cap 10.11.3 or higher? Looks like Apple's got a bug.

**Comment by forthrin** [comment]
Apple reported back to me and [Time Out](https://itunes.apple.com/us/app/time-out-break-reminders/id402592703?mt=12) was the culprit.

**Comment by TermiT** [comment]
Thank you for letting us know!
