### ISSUE TITLE
clipboard doens't store "cut" items 

### ISSUE THREAD

**Issue by RicoLaaa** [TermiT/Flycut#109]
Copied items are stored ont the clipboard, cut items are not and can't be pasted anymore while flycut is in use..

**Comment by MarkJerde** [comment]
Based on an intimate knowledge of the code, that is simply not possible. FlyCut monitors the system pasteboard by polling, so it will become aware of anything that is on the pasteboard regardless of how it got there and will not modify that pasteboard unless instructed to do so by the user. I just tried cutting from TextEdit via cmd-X, pasted without problem into Terminal, and verified FlyCut awareness via the bezel. 

What version of FlyCut are you running? What OS? What program are you cutting from?

**Comment by RicoLaaa** [comment]
test was done on textedit. I tried again this morning and it seems to be working again...
pebkac?
