### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by negativeions** [TermiT/Flycut#110]
I'm on mavericks still, maybe that's it. But sometimes when I click on the menubar icon, the menu would disappear for no reason. I didn't accidentally double click or anything like that. Most of the times it works but so far it seems random. The search bar is bugged. If you have more items in the list such that you need to scroll up and down the search bar will get bugged when scrolling up and down multiple times. Another thing the solution to not copy passwords currently is idiotic. Linus would agree. Why not just have an alternate key combo that doesn't copy whatever to the flycut clipboard instead of trying to autodetect passwords. Seems like common sense.

**Comment by swrobel** [comment]
I have the same issue with the menu disappearing on Sierra PB5

**Comment by zhovner** [comment]
Same here.

**Comment by TermiT** [comment]
Should be fixed in 1.8.2: https://github.com/TermiT/Flycut/releases

**Comment by zhovner** [comment]
Thanks! Works great.
