### ISSUE TITLE
(Question) How can I reset preferences?

### ISSUE THREAD

**Issue by pdf13** [TermiT/Flycut#111]
I tried to change Bazel width and height on Appearance tab, but would like to get default values back. How can I achieve this?

**Comment by sergiopatino** [comment]
Wondering the same.

**Comment by sergiopatino** [comment]
search for folder called com.generalarcade.flycut in /private/var/folders/...
also delete ~/Library/Preferences/com.generalarcade.flycut.plist

anything else?

**Comment by pdf13** [comment]
No, thank you!
