### ISSUE TITLE
Bezel Delay w/ Update to El Cap

### ISSUE THREAD

**Issue by Ballou** [TermiT/Flycut#112]
I love Flycut, it's an indispensable part of my workflow. I've notice though, since updating to El Cap there is a delay (that didn't exist before) when opening the bezel with the keyboard shortcut. I can actually just continue with the key strokes and it still works, even if I don't wait for the bezel to open, but it's just not as tight as it use to be. Would love to correct the delay.

**Comment by TermiT** [comment]
Are you talking about App Store version?

**Comment by Ballou** [comment]
Yup. That’s the one. I didn’t realize there was a non-App Store version. I’ll give that a try.

Thanks!

On Aug 9, 2016, at 11:15 PM, Gennadii Potapov <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you talking about App Store version?
