### ISSUE TITLE
Not working on Sierra

### ISSUE THREAD

**Issue by Bicet** [TermiT/Flycut#115]
On Sierra the app is not working correctly, it starts but as soon as you click on the icon it just show  a flash of the menu.

**Comment by EllDoubleYew** [comment]
I am also running into this same issue on 10.11.6, any idea what is causing this?

**Comment by tvrznikmichal** [comment]
Same issue here but it's working through shortcuts or when you click and hold with two fingers on touchpad or click and hold with mouse

**Comment by TheRojam** [comment]
same issue here.

**Comment by scottharr27** [comment]
Same issue here.

**Comment by edm00se** [comment]
Ditto.

**Comment by TheRojam** [comment]
@edm00se seems a fresh install of flycut fixes the problem?
I already use this release.

**Comment by edm00se** [comment]
I can only confirm what I mentioned above. It appears a full (re-)install occurred.

**Comment by sejmann** [comment]
I'm still using 1.5, and much to my surprise, it works fine running in Sierra on my MBP -- although, I guess I'm using the App Store version -- maybe that's a factor.

**Comment by scottharr27** [comment]
A full reinstall only fixed the problem temporarily for me. But after clicking the menu bar icon a few hours after reinstall, the issue exists gain.

**Comment by dimitrov-adrian** [comment]
+1 for same problem with Flycut 1.8.1 on Sierra

**Comment by TheRojam** [comment]
@scottharr27 thats it.
I reinstalled it freshly a few moments ago and its a bug!
@markjerde please look up and fix it.

**Comment by MarkJerde** [comment]
@TheRojam - I'd have to install El Capitan first. ;-)

**Comment by TermiT** [comment]
I'll look at this next month. Right now I can't update to Sierra – it will probably break my dev environment, which I use for my commercial projects. But you know it's an open source project, if someone would like to help, I would gladly accept patches or suggestions.

**Comment by unkhz** [comment]
Seems to be related to how the searchbox is activated. Disabling the autofocus makes the problem go away.

**Comment by mirfilip** [comment]
I'm on:
```
macOS 10.12.1 (16B2659)
Flycut Version 1.8.1 (1.9adbacf.6.1610)
```
and experiencing it. I've installed flycut via `brew cask`. Using it with shortcuts works perfectly. Using the menu works *sometimes*. It means, I'm sometimes able to make it visible by clicking it many times.

Actually, when I force it to appear and select "About Flycut", the new window appears with the details but as long as it looses focus, it "flashes along" with the menu. I'm able to access it from Expose feature though. I'm not sure if this insight helps anything :)

**Comment by drexlma** [comment]
Same Problem
Flycut Version 1.8.1  
macOS 10.12

**Comment by scutdk** [comment]
Same Problem
Flycut Version 1.8 installed from brew cask
macOS 10.12

**Comment by TermiT** [comment]
Guys, please try 1.8.2: https://github.com/TermiT/Flycut/releases/tag/1.8.2

**Comment by nkalvi** [comment]
Works fine under 10.2.2 - thanks!

**Comment by dimitrov-adrian** [comment]
Works perfect, thanks!

**Comment by Fil** [comment]
How to update the brew thingy?  https://github.com/caskroom/homebrew-cask/blob/master/Casks/flycut.rb

**Comment by igorshubovych** [comment]
For now works like a charm! Great, great, great thanks for update!

**Comment by TermiT** [comment]
I guess I can close it then

**Comment by mazlix** [comment]
@Fil I've never done it before, but I tried to update with `cask-repair` (a script they provide) https://github.com/caskroom/homebrew-cask/pull/28095

**Comment by mirfilip** [comment]
Updated homebrew cask is already available. Thanks a lot @mazlix & @TermiT !

**Comment by Fil** [comment]
Works for me too.  Thanks!

**Comment by drexlma** [comment]
thx work!
