### ISSUE TITLE
Filepath to Flycut Clipboard

### ISSUE THREAD

**Issue by andrewoom** [TermiT/Flycut#119]
The previous version file path was:

`/Users/<user>/Library/Application Support/Flycut/com.generalarcade.flycut.plist` but the newest version doesn't have that path, nor any folder within /Library/Application Support.

Does anyone know the file path to where the clipboard items are saved?

**Comment by MarkJerde** [comment]
It moves around based on build settings like signing. I've assumed that effect is an Apple thing. I don't have my computer handy, but I think you can run the following in Terminal to find it: find ~/Library -name com.generalarcade.flycut.plist
