### ISSUE TITLE
Slow animation for bezel

### ISSUE THREAD

**Issue by postmastersteve** [TermiT/Flycut#120]
I had bezel animation **on** because it is the default.
I noticed that there was too much delay when I press my Flycut key command, and when the popup bezel appeared.

This GIF animation displays what I mean ... as soon a you see the V in my key command is pressed, the waiting begins:

![flycut-slow](https://cloud.githubusercontent.com/assets/275742/21319078/b91e5f46-c5d9-11e6-99f1-ba2063562160.gif)

Analyzing the original video capture, it looks to be just a bit over 1 second before the window actually appears after pressing the key command.

I've discovered that turning **off** bezel animation in Flycut causes the window to appear instantaneously, but I wanted to report the animation has a lengthy delay.

My system:
![2016-12-19_10-59-30](https://cloud.githubusercontent.com/assets/275742/21319212/4d617468-c5da-11e6-8e8d-5c5dd63a911c.png)

**Comment by MarkJerde** [comment]
This is the same as #83, right? I can't recall if it was fixed or just disabled by default. Try a new build if you aren't running the latest

**Comment by TermiT** [comment]
I guess you use MacAppStore build; it's not being updated anymore. I recommend you to download the latest version: https://github.com/TermiT/Flycut/releases
