### ISSUE TITLE
Exclude KeePassX Copies

### ISSUE THREAD

**Issue by gdgp** [TermiT/Flycut#127]
There is the option "Don't copy from password fields" and I have seen other reports about blacklisting this app, but I can't seem to figure it out how to make it work.

Even the option "Include Pasteboard types in clippings list" which I guess should help we set it up properly doesn't seem to do anything.

I'm sure this can be done in the app, but can someone give me a hint on how to do it?

Thank you!

**Comment by pszi1ard** [comment]
I'm also interested as it's far from obvious how to make such an exclusion work.

Why not allow excluding everything based on matching active application name or window title?

**Comment by arnonki** [comment]
+1 On this one

**Comment by stek29** [comment]
The Bezel has app name / icon already.
Can't that be re-used to blacklist apps?

**Comment by MarkJerde** [comment]
@stek29 I haven't looked at your change yet, but it seems reasonable in concept.  The main problem I see is false positives / false negatives.  On macOS there is no mechanism to be notified when the pasteboard is updated (though there is on iOS, but on iOS you can't see the pasteboard while in the background) so we have to poll the pasteboard once a second looking for changes.  The app that Flycut then associates the clipping with is the currently active app, which may or may not be the one that the clipping came from.  I get clippings attributed to Flycut itself fairly often when I open the bezel immediately after doing a copy.  So it becomes a blacklist based on an unreliable informant.  The concerns I would have are:

1. A clipping is expected to be ignored but is not, resulting in a failure of security.
2. A clipping is expected to be remembered but is not, resulting in annoyance.

A more reliable solution could be to fix the "pasteboard types" feature to actually work.  I see KeyPassX lacks any distinct pasteboard types that would be easy inclusion in a blacklist, but it does use "Apple VCard pasteboard type", which may be fairly uncommon and could be a workable one to blacklist on.  VCard is a "contacts card" sort of thing, but I didn't get Address Book to put one on the pasteboard, hence the thought that it might be uncommonly used.

Hope this helps,
Mark

**Comment by stek29** [comment]
@MarkJerde I know it just hopes that updated pasteboard was updated by app which is currently in foreground, but it works good enough for me.

I personally use keepassxc which does not specify any pasteboard type when copying, so I made bundle id filtering.

About unreliability of such method -- well, it's used to make a workaround for MS remote display already, for example.

**Comment by MarkJerde** [comment]
@stek29 - KeePassXC actually uses org.nspasteboard.ConcealedType which is intended to indicate sensitivity of content ([http://nspasteboard.org](http://nspasteboard.org)) and would be the perfect thing to key off of if the existing "pasteboard types" feature were fixed (which is fairly trivial).  I use Apple's ClipboardViewer ([https://developer.apple.com/library/content/samplecode/ClipboardViewer/Introduction/Intro.html](https://developer.apple.com/library/content/samplecode/ClipboardViewer/Introduction/Intro.html)) for doing diagnostics and analysis on pasteboard behavior.

Specific to the Remote Desktop Connection use you mention, in that case the situation is that if the user brings another application to foreground while Remote Desktop Connection is transferring a copy the content will be lost.  From a detection reliability perspective, this would present three scenarios:
1. User already switched foreground app away from RDC -> Copy content is lost -> Flycut doesn't detect the scenario but it is already too late to matter.  No reliability problem.
2. User started copy in RDC and RDC is still foreground -> Flycut detects foreground app is RDC and provides visual indication that the user should not switch foreground app.  No reliability problem.
3. User performed copy outside of RDC and then switched RDC to foreground before Flycut polling -> Flycut detects foreground app is RDC and provides visual indication that the user should not switch foreground app, clearing the visual indication automatically.  The visual indication may not appear at all, may appear and disappear rapidly, or may appear momentarily depending on timing and system load.  No data loss or undesired data retention resulting from reliability.

I hope this makes clear the difference between using an imperfect data point to cause a visual indication and using the same to maintain security of a user's data.  The "we said we'd keep your data safe but we didn't" case is a much bigger issue than the "we caused a blip in your menu bar" case.  Given that KeePassXC has provided a reliable solution via the pasteboard types, I'd stay away from the unreliable solution.

Hope this helps,
Mark

**Comment by stek29** [comment]
@MarkJerde thanks for explaination.
So, the pasteboard type detection is just broken, I guess, and the code from clipboard viewer should provide a good example on how to fix it.

**Comment by MarkJerde** [comment]
@stek29 - I don't know if the Clipboard Viewer has code that would help for this.  I just run it and use its functionality to inspect the clipboard.  To fix the detection, take a look at the NSUserDefaults keys related to detection.  SkipPBoardTypes, I think.  Finding all instance of that text will take you to where it tries to do the detection.  I believe what is happening is along the lines of this pseudocode:
```
let foundPasteboardTypes = [[pasteboard availableTypes] intersectionWith:@[@"NSStringPboardType"]]

if ( [foundPasteboardTypes includes:@"NSStringPboardType"] ) {
  if ( enableSkipPBoardTypes && [foundPasteboardTypes intersectionWith:skipPboardTypes].count > 0 ) {
    return
  }
}
```

So foundPasteboardTypes will only ever have zero or one items in it, and will never have the types you might be interested in skipping even if the actual pasteboard does have them.

Hope this helps,
Mark
