### ISSUE TITLE
Immediate quit 

### ISSUE THREAD

**Issue by clawcha** [TermiT/Flycut#131]
As soon as I open up flycut with my hotkeys it immediately closes. I have tried to change the shortcut but it does not work. I also reinstalled. I am running El Capitan on mac

**Comment by MarkJerde** [comment]
Interesting. Does the Flycut application terminate or just the bezel disappear? What version of Flycut are you running?

**Comment by clawcha** [comment]
I am running version 1.5. The flycut application terminates. When I click on the application icon, nothing opens up at all

**Comment by MarkJerde** [comment]
Ah. That's the App Store version. It's about 5.5 years out of date and cannot be updated due to newer App Store API restrictions. I don't recall off hand what, if any, problems it has with El Cap, but I'd suggest downloading a current version here from GitHub.

**Comment by clawcha** [comment]
wow, ok. Thank you!

**Comment by negativeions** [comment]
I came here to post a comment on this very issue and saw this post. It's happening to me as well. I'm on sierra, latest updates. flycut 1.8.2. It just started doing it today. Very weird. It doesn't exit immediately, but after 30 seconds or so. I just figured out it was happening when I very quickly clicked on the menubar icon when I had a full list of items in it. Once I cleared everything, reloaded flycut, it worked fine. Weird.

**Comment by 1vipulp** [comment]
This was the same issue for me. I download the latest version 1.9.6, but it didn't work on my MAC.

I follow below steps and the issue is resolved. 

> Open Preference for Flycut (by launching it)
> Check the first option from General - "Sticky bezel"
> Try now with your hotkey.
