### ISSUE TITLE
Manage Images

### ISSUE THREAD

**Issue by andreswatson** [TermiT/Flycut#132]
Hi, this is an incredible tool for me VERY useful, the kind of tool that makes me think HOW I COULD WORK BEFORE? :)

The issue / feature I don't find is to work with images / bitmaps items... is that possible? 

Thanks in advance,
Andrés Watson

**Comment by TermiT** [comment]
Sorry, no plans for that

**Comment by stuffmc** [comment]
@TermiT What would it take to offer that? Is it a lot of work? Do you think I should look into it and offer a Pull Request? It would be so useful.

**Comment by TermiT** [comment]
@stuffmc thank you for offering help, I appreciate it! But conceptually, I would like to Flycut operate only with text snippets.

**Comment by stuffmc** [comment]
Would it be okay for you if I fork it and try to make this work for those of us who'd like it? I don't want to steal your code or rename the product, but I really need this option.

**Comment by TermiT** [comment]
Sure, it's open-source, you can do whatever you want :)
