### ISSUE TITLE
style icon on status bar

### ISSUE THREAD

**Issue by mkyc** [TermiT/Flycut#133]
all providers follow some rules of icon standardized layout but not flycut. Example from my view: 
<img width="427" alt="zrzut ekranu 2017-06-01 o 17 16 11" src="https://cloud.githubusercontent.com/assets/28505782/26686882/9e6675f8-46ee-11e7-9458-22b8a2afff3e.png">
This should be changed, to look more professional :)

**Comment by MarkJerde** [comment]
Did you try changing the icon in the preferences (Appearance panel)? I don't know if Dark Mode will automatically invert the black icon, but you can use the white scissors if not. I have nine colorful icons and one black gradient in my menu bar at the moment, fwiw.

**Comment by mkyc** [comment]
Wow, thanks Mark! I haven't seen appearance properties. That works like charm now :) 
<img width="472" alt="zrzut ekranu 2017-06-02 o 18 09 13" src="https://cloud.githubusercontent.com/assets/28505782/26734519/a633ec0e-47be-11e7-8550-62bcfb1f3124.png">
