### ISSUE TITLE
using shift-command-v on multiple displays doesn't work as expected.

### ISSUE THREAD

**Issue by haydonryan** [TermiT/Flycut#134]
If your focus is on one application and in a display, and you do the shift-cmd-v shortcut to browse clipboard, and it's set to display on a different screen, when you release the keys it doesn't paste where you were previously, as the act of displaying the screen in another display changes the focus to that display.

PS Love flycut, recommend it to all my friends, and customers.

**Comment by MarkJerde** [comment]
Hi haydonryan,
Are you using an old release?  This was reported in issue #45 several years ago and fixed in pull request #113 eleven months ago. I still have an old build on one of my systems, and yeah it sure is annoying. 

Hope this helps,
Mark

**Comment by haydonryan** [comment]
I downloaded mine out of the app Store, is that not the latest?

**Comment by MarkJerde** [comment]
App Store must be six or seven years out of date by now.

**Comment by haydonryan** [comment]
ahh ok! I should have read the readme! - my bad!

Thanks Mark, closing.
