### ISSUE TITLE
Dropbox saving does not allow customizing name

### ISSUE THREAD

**Issue by unphased** [TermiT/Flycut#135]
I have 3 Macs that I use. It would appear that if I use flycut's Dropbox sync from more than one that they will trample by using the same filename. 

Need a way to specify a name for the plist or have the hostname be included in the name the plist or the directory that the plist is saved in.

**Comment by MarkJerde** [comment]
I may be misunderstanding your question, but isn't the point of wifi sync to share the clippings store, so separate files would eliminate sharing? Beyond that, I think there are numerous mentions here that the Dropbox sync never really worked well, so it was deleted in https://github.com/TermiT/Flycut/commit/f77c33120a252654f1f1b360eddd3d84c067e9fe. 

Hope this helps,
Mark

**Comment by unphased** [comment]
Interesting. I see what you mean: All 3 of my machines would all synchronize together so that I could paste the same buffer out of any of the machines as long as it syncs. I suppose that would be acceptable, but I'm more after each computer syncing its own copy of them and just having a backup available for each on dropbox. Actually now that I think of it, the existing behavior might be preferable. D'oh!

I'm sad to find out that it's being taken out.
