### ISSUE TITLE
Delete an entry!!!

### ISSUE THREAD

**Issue by kunal394** [TermiT/Flycut#137]
How do I delete an entry from my list?

**Comment by MarkJerde** [comment]
Press the delete key when the clipping you want to delete is displayed in the bezel.

**Comment by kunal394** [comment]
It's not working in mac sierra

**Comment by kunal394** [comment]
can i change it from somewhere else? i mean directly from the file the list is stored in?

**Comment by MarkJerde** [comment]
Are you using a funny keyboard? Try backspace, delete, fn-backspace, fn-delete.

You can edit the file in Library, but you'd have to find it and you'd have to learn about clearing macOS plist caches.

**Comment by kunal394** [comment]
Alright thanks! Plan on clearing the cache.

**Comment by MarkJerde** [comment]
I forgot to follow up on this to report that the delete key on my MacBook Pro keyboard is working just fine to items from the Flycut store.  Note that this is a feature of the Bezel (shift-command-v) and not the menu.

If you are comfortable debugging, you could breakpoint the lines following "switch (pressed)" line in AppController.m to see what character your keyboard is sending.  The recognized characters are NSBackspaceCharacter and NSDeleteCharacter.  NSDeleteFunctionKey is explicitly ignored for whatever reason.

This feature dates back to late 2011 and is present in the second App Store release of Flycut (Dec 2011) and not the first release (mid 2011).

Hope this helps,
Mark
