### ISSUE TITLE
Supporting Images in Flycut

### ISSUE THREAD

**Issue by ans45** [TermiT/Flycut#143]
I'm considering having someone on Upwork build in support for images. Would this be useful?

**Comment by zhovner** [comment]
Yeah, it will be great. I can donate few $ for this.

**Comment by ans45** [comment]
Great! Here's the listing - https://www.upwork.com/job/Add-Copy-Paste-Image-Support-Flycut_~0158f96d25ea680f2e/

**Comment by ans45** [comment]
Do you want to try try and have a contractor on upwork create it?

**Comment by zhovner** [comment]
Sorry, I don't understand what you asking.

**Comment by ans45** [comment]
I have two proposals on upwork. One bid is 150$ and the other is for 40 hrs (don't know how much this would translate into dollars yet). A few questions. Do you think those are reasonable offers? Do you want to pursue the offer? Do you know anyone else that might want to throw in a few dollars to spread the cost around?

**Comment by stek29** [comment]
#132 duplicate

**Comment by tmm** [comment]
is this still active? i would pay for some of the work.

**Comment by pleasejust** [comment]
Can you make this download available please? thanks.

**Comment by bgmort** [comment]
Was this only closed because nobody wanted to implement it? I'll put up a few bucks for it as well.

**Comment by MarkJerde** [comment]
This was closed as it had been mentioned to be duplicate of another issue, and in that issue the subject matter was discussed to be outside of the vision of Flycut.
