### ISSUE TITLE
Automatic Login

### ISSUE THREAD

**Issue by w4rner** [TermiT/Flycut#167]
Even though I don't have 'Launch Flycut on login' ticked:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/31451410/48973970-9a61a180-f011-11e8-9d74-f87df61d5083.png">

my computer launches FlyCut on login. I've noticed in System Preferences > Users & Groups, that FlyCut is here:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/31451410/48973958-874ed180-f011-11e8-8b60-0d2fd00f1b56.png">

Any ideas why?

**Comment by MarkJerde** [comment]
It’s possible that the 3rd-party component than registers login items (UKLoginItemRegistry, I think) is no longer compatible with new macOS versions. What OS version are you on? Would you have previously set Flycut as a login item?

The login item utility is also very slow, so it could be a complication of that slowness. If you check and uncheck “Launch Flycut on login” does that fix it?

Another possibility could be that you have multiple copies of Flycut, one of which is registered as a login item and the other of which is the one you showed the preferences panel from, but I’m pretty sure you would have realized that so probably not your solution. 

Hope this helps,
Mark

**Comment by lpwarner** [comment]
Mark,

Thanks for your response. 

"If you check and uncheck “Launch Flycut on login” does that fix it?" Yes - this actually worked!

I'm on MacOS Mojave.

L

**Comment by drvdijk** [comment]
Thanks for the wonderful app! Using it for years, never fails, not in the way, ie perfect!

I just reinstalled Mojave fresh, and noticed Flycut didn't auto-start anymore. The checkbox in the preferences doesn't seem to have any effect. Adding it in the system preferences _does_ work for me (although that's considered slow?). Should it work through the checkbox? Is that the preferred way?

Thanks!
