### ISSUE TITLE
Flycut not working on macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by ygit** [TermiT/Flycut#171]
FlyCut was working fine on older macOS versions. Right now I'm not able to paste from the Clip History. It was working fine in Catalina Beta versions as well, something seems to be broken by Catalina. I'm using the latest Flycut version, keenly awaiting fix for the issue.

**Comment by wrightmhw** [comment]
An additional/related issue... all flycut preferences are reset after a restart. Hotkey and appearance settings do not hold their value.

**Comment by twknab** [comment]
I run Flycut on latest ver Catalina, no problems on my end.
