### ISSUE TITLE
Ability to block copies from named applications

### ISSUE THREAD

**Issue by shawvid** [TermiT/Flycut#172]
It would be good from a security standpoint to enable the user to list specific applications from which they do not want Flycut to copy text.  The most urgent use case is with password apps.  The one I use, OneSafe, copies all text to the clipboard as NSStringPboardType, which I believe indicates simple standard text.  For that reason, if I include this clipboard type in the "Don't copy from password files > Pasteboard types", it would block all text.  I would assume OneSafe is not coded correctly to indicate a Password PboardType, but there may be other password applications that have the same flaw.  I would love to move all my passwords to another password app, but who has time to mess with that :-)

I would love to be able to tell Flycut to ignore all text from OneSafe.  

Thank you!

**Comment by MarkJerde** [comment]
Hi @shawvid. That would be a nice ability but it is outside of the options available in macOS. We can only make a guess what app a clipping came from, and it's easy to get it wrong. Details here: https://github.com/TermiT/Flycut/issues/127

Best wishes!
Mark

**Comment by shawvid** [comment]
Mark,

I really appreciate the feedback and the very informative linked discussion.  It all makes perfect sense.  It is probably the right decision for your product and most customers.

Sadly for me, I will have to use an alternative app that enables app blacklisting.  I do presentations and demos for my job and will occasionally need to access Flycut during a demo.  This could be in front of dozens of people.  I don’t want them to see the password to my bank website by accident, for example.  The risk of showing a password is too high.  This is risk of using another clipboard manager that might mis-identify the source application will likely be far less dire.

Thank you again for your information.  

-----------------
Shawn Zerby
419-571-3369 m

**Comment by mann** [comment]
@shawvid, you mentioned that you will have to use an alternative app that enables app blacklisting. What app you were able to settle on to solve your issue? Your issue is very similar to mine.

**Comment by mann** [comment]
@MarkJerde or anyone else. Is there a place I can go to better understand how to properly use the Pasteboard Types field within the Flycut preferences? I tried to change the field to "org.nspasteboard.ConcealedType" to solve for Flycut copying KeePassXC copied info to the Flycut clipboard which I am trying to avoid.

**Comment by drorata** [comment]
@mann were you able to figure this out?
