### ISSUE TITLE
loss of formatting

### ISSUE THREAD

**Issue by mrbennbenn** [TermiT/Flycut#173]
when I paste the text I lose all formatting, e..g bold, bullets, para spacing. This needs to be resolved.

**Comment by NickHibma** [comment]
From what application are you copying what content and into which application and field are you pasting it?

**Comment by mrbennbenn** [comment]
I copied the information from body of email on Gmail (on Chrome, on macbook
pro) and pasted it into another email body. I also tried copying the master
text from Textedit (on same mac) to email body. On all occasions the
formatting was lost.

**Comment by MarkJerde** [comment]
Hi mrbennbenn,
Flycut has never preserved formatting. That is, it won’t interfere with the normal pasteboard, which does preserve formatting, but clippings recalled from Flycut will only contain the characters, whitespace, and line feeds. The Mac pasteboard uses complex multi-type clippings and Flycut only targets the raw text portion of that. 

Hope this helps,
Mark

**Comment by TermiT** [comment]
We are keeping it simple, so no support for storing formatting in clips
