### ISSUE TITLE
Update requires ENTER keystroke to paste from Flycut

### ISSUE THREAD

**Issue by VanToai** [TermiT/Flycut#179]
Hi folks! Been a big fan of Flycut for a long time! Quick issue:

The recent update requires me to press ENTER to paste from Flycut. Previously, if I simply released Command+Shift+V, Flycut would paste. 

I preferred the former method because it required fewer keystrokes and was faster with my workflow. 

Please revert to the previous workflow, or at least provide the toggle option to "Paste on release" vs "Paste on ENTER"

**Comment by TermiT** [comment]
OS version? Tried to disable "Sticky Bezel"?

**Comment by VanToai** [comment]
Thank worked! Thanks, I didn't realize that's what that option meant. Not clear.
