### ISSUE TITLE
Menu selection pastes and Remove duplicates not working in 1.9.4 (macOS High Sierra 10.13.6)

### ISSUE THREAD

**Issue by Ikemitsu1** [TermiT/Flycut#180]
"Menu selection pastes" and "Remove duplicates" are not working for me. I have the Mac App Store version 1.9.4 (6) running on macOS High Sierra 10.13.6. Also enter doesn't paste from the bezel.

**Comment by TermiT** [comment]
I can confirm "Remove duplicates" issue is a bug.
Regarding "Menu selection pastes" try to use https://github.com/TermiT/Flycut/releases

**Comment by Ikemitsu1** [comment]
Menu selection pastes doesn't work in 1.9.3 (5) either but it works in 1.9.2.

**Comment by TermiT** [comment]
@Ikemitsu1 I've added 1.9.4 without sandboxing. It should work fine.

**Comment by Ikemitsu1** [comment]
Yes, Menu selection pastes and Remove duplicates both work. Thank you!
