### ISSUE TITLE
[Solved]Flycut will not paste unless I hit Enter

### ISSUE THREAD

**Issue by threewordphrase** [TermiT/Flycut#183]
Flycut used to paste without needing to hit enter. Recently, I started having to hit enter.

This is either a bug or a feature I would like to disable.

**Comment by dunnkevin** [comment]
Hey @threewordphrase. Not associated with FlyCut at all but ran into this same issue. This feature can be disabled in the preferences by toggling off "Sticky Bezel", looks like this may have been enabled by default in the latest version.

**Comment by threewordphrase** [comment]
That did it @dunnkevin , thanks!
