### ISSUE TITLE
Upgraded Flycut to 1.9.4, Pasting No Longer Works, View Freezes

### ISSUE THREAD

**Issue by mstruve** [TermiT/Flycut#184]
Hi I recently upgraded Flycut and while I love the additional data of what the copy came from, pasting no longer works and the screen freezes until I quit the app. Some screen shots below. 

<img width="514" alt="Screen Shot 2020-02-01 at 2 15 43 PM" src="https://user-images.githubusercontent.com/1813380/73597774-c45c0100-44fd-11ea-95ef-e6147a85bacd.png">
<img width="576" alt="Screen Shot 2020-02-01 at 2 16 02 PM" src="https://user-images.githubusercontent.com/1813380/73597775-c45c0100-44fd-11ea-9028-cda02a41da76.png">

I tried Clearing everything and restarting my computer but it still freezes everything when I try to paste from it.

**Comment by TermiT** [comment]
What OSX version do you use? Is "Sticky Bezel" enabled?

**Comment by mstruve** [comment]
It was enabled, not sure if that default came with the new version or not as I haven't touched my Flycut setting since I installed it. I disabled it and things seem to be working again so I will close this. Thank you for your guidance! 

For reference, my OSX version is 10.14.6.
