### ISSUE TITLE
Flycut stopped pasting.

### ISSUE THREAD

**Issue by iaisic** [TermiT/Flycut#187]
My MacBook Pro (MacOS Catalina 10.15.3) automatically updated to Flycut Version 1.9.5 (7).
Paste does not work anymore.  It only cycles the chosen text to the top of the list and puts in the system clipboard (so I can still do Command-V to paste).

**Comment by TermiT** [comment]
Give Flycut access in System Preferences -> Security & Privacy -> Privacy -> Accessibility. If you had the previous version of Flycut installed, you might need to remove if from Accessibility first and add it again.

Also, you may want to disable "Sticky Bezel" in preferences

**Comment by iaisic** [comment]
Thank you Gennadii!
Indeed, I had to remove Flycut from the Accessibility and then add it back.

Best,

אִילָן אָייזִיק
ILAN AISIC
+972-52-4815533

**Comment by iaisic** [comment]
Hi again,
The same problem re-appeared.
I again removed Flycut from the Accessibility Privacy list in my System
Preferences/Security & Privacy and then added it again.  This time it did
not help.  However, after quitting the running app and restarting it.  It
works ok.
I have no idea why this happened again.   I tried locking my screen and
reentering but it did not reproduce the issue.
I'll let you know when it happens again.
--
אִילָן אָייזִיק
ILAN AISIC
+972-52-4815533
