### ISSUE TITLE
Save functionality not working; Flycut toggle bug

### ISSUE THREAD

**Issue by rafiron** [TermiT/Flycut#188]
As per the help link [https://github.com/TermiT/Flycut/blob/master/help.md](https://github.com/TermiT/Flycut/blob/master/help.md) if I press s key then Flycut saves the file on desktop. This however isn't happening. I have activated the sticky bezel mode and then trying this out. 

Can someone let me know, if I'm doing something wrong here or is this a bug.

Also saw a bug where if the Menu item icon is changed and I click on it while pressing option key and do it 2-3 times, the Menu item icon disappears or sometimes showing some other kind of Menu item which wasn't selected in the settings.

Using the Flycut version 1.9.5 on mac os Catalina 10.15.3

**Comment by TermiT** [comment]
App Store doesn't have this functionality, Apple's sandboxing restrictions
