### ISSUE TITLE
SUGGESTION: Use the mouse scroll wheel instead of arrow keys

### ISSUE THREAD

**Issue by mbernal131** [TermiT/Flycut#19]
I absolutely LOVE this app, so first off a big thank you from me to you.

Now the one thing I would really love to see is when the bezel is up you have to use the arrow keys to scroll through your previous cuts. I would like to see something in the preferences that enables the scroll wheel to cycle through the bezel cuts if the Bezel is active. 

I think this is a very simple suggestion that would really take this to the next level!

**Comment by TermiT** [comment]
implemented in 1.8
