### ISSUE TITLE
Flycut doesn't open after recent update

### ISSUE THREAD

**Issue by pawelski-inc** [TermiT/Flycut#191]
When I try to open Flycut after the most recent update it doesn't open, there is no error message, simply nothing happens.

I have restarted my machine, deleted Flycut and installed it again, but there are no changes, it doesn't open still.

I'm on OS X El Capitan V 10.11.6, using Flycut V 1.9.5

**Comment by TermiT** [comment]
Apple made it very hard to test apps on old OSX versions. Something probably has broken and I don't have a way to test. You can try one of older versions from here: https://github.com/TermiT/Flycut/releases
