### ISSUE TITLE
Delete individual or blocks of saved items

### ISSUE THREAD

**Issue by mwurth8** [TermiT/Flycut#20]
I have just started using Flycut and so far like the program very well, but I would like to keep some of the entries long term as I use them over and over and some of them I would never use again. It seems that the only option  is to Clear All of the entries. Is there not a way to right click or highlight entries that you don't want any longer and send them to the trash bin or delete them?

**Comment by NickHibma** [comment]
Actually, it does work without 'sticky' bezel. I just copied three words, and, while holding Command, or holding Command+Shift was able to delete entries.
