### ISSUE TITLE
Launch Flycut on login... except when it doesn't.

### ISSUE THREAD

**Issue by GwynethLlewelyn** [TermiT/Flycut#206]
I have a very-hard-to-reproduce issue.

I hardly reboot and/or log off my MacBook Pro (Retina, 15-inch, Mid 2014), currently running macOS Big Sur Version 11.0 Beta (20A5323l) after an upgrade earlier today, but it _seems_ to me that (at least after an operating system upgrade), Flycut 'forgets' to be launched on login. In other words, after a reboot, Flycut does _not_ launch in spite of that checkbox theoretically being on... and, on opening Flycut Preferences after a reboot, the checkbox is indeed off! So I check it again, and forget about the setting for some weeks or months, until a new macOS upgrade comes along, the MacBook needs to reboot again, and, once more, Flycut does not launch, and the checkbox is off... and so forth, _repeat at nauseam_.

Why is that so hard to reproduce...? Well, it does _not_ happen that way _all_ the time. In fact, it's rather unpredictable _when_ it happens (much less _why_). I've seen reboots where Flycut _did_ launch on start, but I cannot say what was different at that time (except, of course, that macOS upgrades _may_ not be always changing the same files/configurations in the same way — and possibly in some cases it touches something that makes Flycut 'forget' it's supposed to be launched on login, and in some cases that does not happen...). It's thus impossible to predict _if_ Flycut will forget the 'Launch Flycut on login' checkbox on the next reboot...

Oh, and I confirm that _all the other options are correctly saved_ between as many reboots as possible... even when doing a 'major' upgrade (say, the jump from Mojave to Catalina, or from Catalina to Big Sur), the list of items on the Pasteboard remains as it was before the reboot! It's _only_ the checkbox for 'Launch Flycut on login' that may not 'survive' a reboot...

I wonder if this is some kind of weird security feature that requires activation (or deactivation...) for Flycut to be able to restore its status to launch itself at login. It's been a long time since I had to do something like that on an application — macOS is far more clever these days, and all sorts of upgrades are much more 'safer' and very predictable than, say, a decade ago...

**Comment by alhoqbani** [comment]
The option "Launch Flycut on login" does not persist. I check the option, and when I reopen the preferences I find it unchecked. 

I'm on macOS Catalina Version 10.15.5

**Comment by GwynethLlewelyn** [comment]
Ok, that worked for me, @alhoqbani — thanks for the tip! So basically the only thing that doesn't work is for Flycut to add itself to the Users & Groups preferences...

**Comment by chrisparker2000** [comment]
I'm on Mojava 10.14.6, and the "Launch Flycut on Login" does not persist for me either.  Running 1.9.4

**Comment by bcalmac** [comment]
Same experience on Catalina 10.5.6. After I restart Flycut, the option is no longer checked. It must be that it wasn't saved in the first place.

**Comment by Kignuf** [comment]
Same experience here, thanks for the tip @alhoqbani !

**Comment by simonc** [comment]
Hello. Same problem here under Monterey. ❤️

**Comment by ekurer** [comment]
Maybe better to guide users to add Flycut to login items in Users & Groups preferences as @alhoqbani explained.

**Comment by GwynethLlewelyn** [comment]
@ekurer agreed; let me close this issue, as technically it has been solved (it's just not clearly documented).

**Comment by AuctionEdgeDevOps** [comment]
Same issue here, I'll follow solution above.
Mac: Big Sur (11.6.5)
Flycut: 1.9.6 (9)

**Comment by bhaavanmerchant** [comment]
Same issue here, I'll follow solution above.
Mac: Monterey (12.6.1)
Flycut: 1.9.6 (9)

This issue shouldn't be marked as "Closed".

**Comment by kravchuk-ivan** [comment]
Same issue here, I'll follow solution above.
macOS: 26.2
Flycut: 1.9.6 (9)
