### ISSUE TITLE
password-store cannot clear after PASSWORD_STORE_CLIP_TIME

### ISSUE THREAD

**Issue by Callisto88** [TermiT/Flycut#209]
Hi,

First of all thank you for this amazing tool ! I am using it everyday and it's a must have !

I am using it in combination with password-store, especially the option `show -c` to get the password not displayed but directly copied into the clipboard ; which is working fine.

The actual behaviour of password store is to clear the password after `PASSWORD_STORE_CLIP_TIME`, unfortunately this specific action does not work =(

Testing the following command :

```
pass show -c passwordstore-entry 2>&1 >/dev/null
```

brings the password into the clipboard of flycut

BUT never get cleared after `PASSWORD_STORE_CLIP_TIME` (default is 45 seconds)

If it helps i noticed that when there is at least two entries in flycut ; the password just go to the second place instead of being cleared whereas when it's the only entry nothing happens

OS X version : 10.15.6 (Catalina)
Flycut version : 1.9.4
pass version : v1.7.3

Thank you in advance for your help

**Comment by MarkJerde** [comment]
Hi Callisto88. The feature to clear the pasteboard is just a feature of your password manager and has no bearing on the actual pasteboard data or what any other app who observes or receives from the pasteboard does with that clipping.

Flycut observes the pasteboard once a second and stores the plaintext content of the pasteboard.

In the preferences you can find an option to ignore any clipping which: has no spaces, has at least one digit, has at least one upper case letter, has at least one lower case letter, has at least one symbol, and has a length matching one of the lengths you provide in a list. This provides a reliable way to avoid capturing passwords if you use random passwords of specific length without causing false positives. 

Another option is to Ctrl-click the menu item to disable pasteboard observation, then Ctrl-click again to reenable. The icon changes to reflect this. 

Hope this helps,
Mark

**Comment by Callisto88** [comment]
Hi @MarkJerde, thank you for your answer !

I saw this option in the preferences that allows you to filter was will be clipped or not, unfortunately in my case it's quite difficult to find a pattern for the passwords without have false positive with non-password text. Useful in othercase though. 

I will submit this issue to the password-store team then

Cheers
