### ISSUE TITLE
Icloud

### ISSUE THREAD

**Issue by tommo69** [TermiT/Flycut#210]
iCloud sync doesn’t seem to work bitween iOS devices. iPad and iPhone both iOS 13 just don’t sync.

**Comment by tommo69** [comment]
iPad doesn’t see I phone clips At all. 
iPhone seems to see something, seems like it’s loading the clip, but then it doesn’t.

**Comment by theappaffair** [comment]
Flycut cannot sync copied items on iCloud for me ass well. Flycut has a list of copied items on my Mac but there's nothing on my iPhone app (even though they are on the same iCloud account). Flycut, am I doing something wrong here or is there a fix?

**Comment by TermiT** [comment]
for iCloud between Mac and iPhone you need to use the following fork: https://github.com/MarkJerde/Flycut
