### ISSUE TITLE
capability to manipulate flycut data using command line

### ISSUE THREAD

**Issue by narendravardi** [TermiT/Flycut#212]
Hi @TermiT,

Thanks for the great product!

Just wanted to check if there is any command line tool interface for manipulating flycut data.  (By data I mean the clipboards that are copied and stored)

I work frequently on command line and this would be good thing to have for me.

**Comment by MarkJerde** [comment]
Hi @narendravardi,
I've wanted the same from time to time, and figured someday I'd port FlyCut to the command line, but now just thinking about it, as long as you have `Save` `After each clip` in your settings, you can just use the save file from the command line.

Use this command to find the file they are saved in: `find ~/Library/Preferences|grep -i "flycut.*plist"`.

Then this command will show you the most recent clipping: `/usr/libexec/PlistBuddy -c "Print store:jcList:0:Contents" test.plist` (where `test.plist` is replaced by the path to your file in ~/Library/Preferences). Change the `0` to another number to access a different index in the history.

Hope this helps,
Mark

**Comment by narendravardi** [comment]
Hi @MarkJerde,

Thanks for the sharing these details. Very informative. 

One problem I have faced in this is that the data present in `test.plist` is outdated. It seems to be a backup. Not the exact data available at realtime. Have you faced similar issues as well?

**Comment by MarkJerde** [comment]
Hi @narendravardi,
It sounds like either you found an old location of the plist (the filename and location is dependent on some build settings and has moved over the years) or the Save After each clip I mentioned isn’t selected or you are using an old version of Flycut. With that setting it does write the save file promptly. 
- Mark

**Comment by Callisto88** [comment]
Hi @MarkJerde 

I have been looking for such feature because i use password-store to manage my password ; unfortunately password-store does not implement item deletion for clipboard manager like Flycut ( only for Klipper at the moment ) cf. https://git.zx2c4.com/password-store/tree/src/password-store.sh#n183

I would like to be able to run a such command line `/usr/libexec/PlistBuddy -c "Print store:jcList:0:Contents" test.plist` but that would delete copied password. Any chance to achieve with PlistBuddy commands ?

This would be great as i do not want password to be kept in the clipboard.

Thank you

**Comment by MarkJerde** [comment]
Hi @Callisto88,
Nope. PlistBuddy could certainly edit that file, but Flycut only reads that file on launch and would overwrite it prior to that undoing the changes. There are no command line mechanisms to manipulate Flycut. The closest would probably be to use Automator to synthesize the keystrokes to control Flycut and then invoke that from the command line. 

Mark

**Comment by Callisto88** [comment]
Hi @MarkJerde 
Thank you for your answer ! Using Automator was a good idea ! I just finished to setup an appleScript that delete the last entry from FlyCut and it works great !

Here is the gist if anyone is interested in https://gist.github.com/Callisto88/5466ee238a80293333be29950f86ed43

Cheers

**Comment by plt3** [comment]
> find ~/Library/Preferences|grep -i "flycut.*plist"

Does anyone know where Flycut stores this data now? Running the above command doesn't find anything on my machine.

**Comment by jbylina** [comment]
I found it here:

```
cat /System/Volumes/Data/Users/$(whoami)/Library/Containers/com.generalarcade.flycut/Data/Library/Preferences/com.generalarcade.flycut.plist
```

To preview XML:
```
cat /System/Volumes/Data/Users/$(whoami)/Library/Containers/com.generalarcade.flycut/Data/Library/Preferences/com.generalarcade.flycut.plist | plutil -convert xml1 -o - - 
```

**Comment by plt3** [comment]
> I found it here:
> 
> ```
> cat /System/Volumes/Data/Users/$(whoami)/Library/Containers/com.generalarcade.flycut/Data/Library/Preferences/com.generalarcade.flycut.plist
> ```
> 
> To preview XML:
> 
> ```
> cat /System/Volumes/Data/Users/$(whoami)/Library/Containers/com.generalarcade.flycut/Data/Library/Preferences/com.generalarcade.flycut.plist | plutil -convert xml1 -o - - 
> ```

Thanks @jbylina, and sorry for such a late reply. Running your command does give me Flycut data, but it looks like it is from about 2 weeks ago for me (both the data in the plist and the file modification timestamp), even though I have been using Flycut since. Do you have any idea why that is?

**Comment by MarkJerde** [comment]
@plt3 It sounds like you don't have `Save` `After each clip` in your Flycut settings. It's probably set to only save to that file when Flycut quits. Changing to save after each clip will write to that file after each clip.

Hope this helps,
Mark

**Comment by plt3** [comment]
@MarkJerde that was exactly it. Thank you!
