### ISSUE TITLE
Launch Flycut on Login option not saving

### ISSUE THREAD

**Issue by thecomputerguyjeff** [TermiT/Flycut#236]
1.  Go into preferences, and check 'Launch Flycut on login', and close preferences
2. Quit flycut
3. Go back into preferences, I find that it is no longer checked.
OR
1.  Go into preferences, and check 'Launch Flycut on login', and close preferences
2. Restart computer
3. flycut does not start on login AND I find that when I open preferences, it is no longer checked

Note: I did change the remember quantity from 40 to 99 and that did save.

flycut 1.9.6 (9)
macOS 10.15.7

**Comment by Jacko1394** [comment]
Yep exactly what I am experiencing too - quite annoying
I'm on a M1 MacBook if thats relevant?

**Comment by mconigliaro** [comment]
I'm not sure if it's related, but it seems like Flycut is undoing this setting on startup. Steps to reproduce:

1. Open Flycut
1. In preferences, enable `Launch Flycut on login`
1. Run `defaults read com.generalarcade.flycut loadOnStartup` (it returns `1`)
1. Quit Flycut 
1. Run `defaults read com.generalarcade.flycut loadOnStartup` (it still returns `1`)
1. Open Flycut
1. Run `defaults read com.generalarcade.flycut loadOnStartup` (it returns `0`)
1. Check preferences again and `Launch Flycut on login` will be disabled

**Comment by mconigliaro** [comment]
Duplicate: #206

**Comment by rdadoune** [comment]
I'm also experiencing the same issue.

**Comment by jwfriese** [comment]
This is still happening for me on the latest version that I'm able to get from a Homebrew cask install: 
```
..t-trigger-for-notifications↑1|✚2] ❯❯❯ brew info --cask flycut
==> flycut: 1.9.6
https://github.com/TermiT/Flycut
/opt/homebrew/Caskroom/flycut/1.9.6 (120B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/flycut.rb
==> Name
Flycut
==> Description
Clipboard manager for developers
==> Artifacts
Flycut.app (App)
==> Analytics
install: 3 (30 days), 588 (90 days), 6,334 (365 days)
```

Does Homebrew not get the latest releases anymore?

**Comment by rdadoune** [comment]
The code never got released, it doesn't seem like this project is maintained. I switched to https://github.com/p0deje/Maccy
