### ISSUE TITLE
Possibly incorrect boolean value when calling SMLoginItemSetEnabled

### ISSUE THREAD

**Issue by MarkJerde** [TermiT/Flycut#253]
Hi TermiT,
I'm just getting around to reviewing some merged changes and noticed that in `toggleLoadOnStartup:` the same `SMLoginItemSetEnabled` call is made in both the enabled and disabled paths. (The line of code is identical.) I'm pretty sure it should be `NO` in the second case, but wanted your input before changing it. I'll include the change in a PR soon if you agree.

https://github.com/TermiT/Flycut/blob/14486cecab279327eaa09037d36637a85f3da364/AppController.m#L698

Thanks and best regards!
Mark

**Comment by TermiT** [comment]
Yes, definitely copy-paste issue :( Thanks for catching it.

**Comment by GreenRecycleBin** [comment]
This should be closed since it was fixed in #254.
