### ISSUE TITLE
A simple suggestion

### ISSUE THREAD

**Issue by sslocal530** [TermiT/Flycut#26]
I don't know if this is the right place to put this but...

I love jumpcut and the one feature I would love is if there was an option to save 5 or 10 "clips" permanently. I would love to be able to have certain things always at my disposal, like my address, an email adress, a tracking number. The possibilities are endless

**Comment by jasonrhaas** [comment]
+1 for this feature

**Comment by MarkJerde** [comment]
This was added five months ago in #80. I guess this issue and #75 are duplicates so this issue didn't get linked in at that time.
