### ISSUE TITLE
[Feature Request] - Permanent Items

### ISSUE THREAD

**Issue by jasoncarmer** [TermiT/Flycut#260]
I love this app and use it all day everyday.  Its great!

I find myself using the same 5 or so strings often, login scripts, email addresses, phone numbers.

What would be great is if Flycut had an area with top10 permanent items, maybe in the preferences.
If I could store things I always want and then press cmd-sft-v to bring up flycut then 1-9

so cmd-sft-v then 1 -> paste my email address that I have store in the preferences
or cmd-sft-v then 2 -> paste my phone number from preferences
and so on 1-0

I'd have to remember what I stored in each preference number but thats on me.

This would be a great feature ... thanks for considering this upgrade.  Jay

**Comment by MarkJerde** [comment]
Hi @jasoncarmer 
It sounds like you are looking for the Favorites feature. Just type “f” in the bezel to switch to the Favorites store (yellowish background) and again the return to the main store. Type an uppercase “F” to move the current clipping between the two. 
Mark

**Comment by jasoncarmer** [comment]
Oh wow, I've been using this app for a while now and I never knew about the favorites.

That is great thanks for the info and quck response.
