### ISSUE TITLE
Cannot disable clibboard sharing

### ISSUE THREAD

**Issue by bmidgley** [TermiT/Flycut#273]
I have flycut on two macs on the same wifi. I've disabled clipboard sharing through icloud, but they do it anyway. As soon as I copy something into one computer's clipboard, I see it in the other one's dropdown.

It's not clear this happens because of handoff. I suppose flycut is unaware of what handoff is doing. Maybe documenting this would be a good mitigation.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/63477/185677526-528a4ff0-5a6c-44da-b345-f2b7bb2a1d0e.png">

**Comment by bmidgley** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/63477/185677990-1096a78c-ee99-41cc-a6ab-5a19e8f27961.png">

**Comment by MarkJerde** [comment]
Hi @bmidgley 
It sounds like your Macs are sharing their pasteboard. That’s a MacOS feature which Flycut doesn’t have any involvement in. Flycut monitors your pasteboard, so if there’s something on your pasteboard then Flycut will capture it, and if you have that MacOS feature turned on then that’s a way things can get onto your pasteboard. 
Hope this helps,
Mark

**Comment by bmidgley** [comment]
yes thanks. closing now
