### ISSUE TITLE
Menu Selection not Pasting when Selected

### ISSUE THREAD

**Issue by mstruve** [TermiT/Flycut#289]
Hi all, 

I got a new M2 Macbook Pro and am trying to use Flycut with it. The "Menu Selection Pastes" option is chosen but not being respected. 
<img width="518" alt="Screenshot 2023-08-26 at 7 13 03 PM" src="https://github.com/TermiT/Flycut/assets/1813380/813c22a3-2077-459d-b523-107eb207958d">

Flycut Version 1.9.6 
OSX Ventura 13.5.1

I have the same versions on my old machine (2019 Macbook Pro) and it works fine. Any suggestions on how to get it working correctly on the new machine? I tried uninstalling and reinstalling it as well as restarting the machine.

**Comment by craigfurman** [comment]
I was in the same position, with a new m2 macbook pro, and solved it by allowing flycut to control the computer in Settings -> Privacy & Security -> Accessibility

**Comment by mstruve** [comment]
I had that turned on but decided to give it another toggle and then do a restart and now it works! Thank you!
