### ISSUE TITLE
Unable to paste from clip board.

### ISSUE THREAD

**Issue by itsluisjim** [TermiT/Flycut#301]
I recently updated to MacOS Sequoia 15.0 and fly cut has stopped working.

It registers when I copy some text but I can't paste anything from my clipboard by triggering the hotkey.

<img width="482" alt="Screenshot 2024-09-24 at 1 03 42 PM" src="https://github.com/user-attachments/assets/c5fc0740-9dd0-498f-9ba0-520d78c0ee5f">

![Screenshot 2024-09-24 at 1 03 17 PM](https://github.com/user-attachments/assets/aec16842-221b-4972-993d-184068dcb68c)

**Comment by itsluisjim** [comment]
nvm. conflicting hotkey.

**Comment by drorata** [comment]
I have the same issue. If I restart FlyCut it works, and then after a while it stops --- when pressing the hotkey I can see the clipboard but when I release it nothing is pasted (there's a beep).

I don't understand how to solve this based on @itsluisjim answer... Does it mean that there's another app that uses the same hotkey? Even though that the hotkey does bring up the FlyCut menu?

NB: Is there a way to know which other app conflicts with the hotkey?
