### ISSUE TITLE
Preferences not saving

### ISSUE THREAD

**Issue by douglsmith** [TermiT/Flycut#36]
I've had an issue where the preference were not preserved if Flycut was quit and then launched again. All the preferences went back to defaults.

It may be tied to the Clippings Save option. I had it set to "Never". I recently changed it to "On Exit" and then my preferences were preserved.

I then tried changing it back to "Never" and all the settings were preserved except the Clippings Save option, which went back to "On Exit". The same was true for "After each clip". That setting would stay, but "Never" would not.

**Comment by JoseAlban** [comment]
I had this issue on version 1.5 (2011) recently on OS X 10.8.5, and realised that checking the preference "Dropbox Sync" was screwing it up.

Now I've it unchecked and it saves my preferences normally when I quit.

**Comment by bool-dev** [comment]
Still not fixed!! On El Capitan.

**Comment by TermiT** [comment]
Version 1.8?

**Comment by bool-dev** [comment]
@TermiT Sorry missed your comment. Version 1.5 from AppStore, any reason that isn't updated as yet?

**Comment by TermiT** [comment]
@bool-dev Apple forbids to use CGEventPost call for sandboxed apps. And this part is very import as we use CGEventPost to emulate Command+V shortcut. So there is no way to update AppStore version without breaking main functionality.

**Comment by bool-dev** [comment]
@TermiT thanks for explaining that! Done, 1.8 works as expected!
