### ISSUE TITLE
add formula or cask to homebrew

### ISSUE THREAD

**Issue by lanterndev** [TermiT/Flycut#38]
Just noticed there's a cask for Jumpcut (see phinze/homebrew-cask#56) but not Flycut, which is better! As Flycut's maintainer, would you be interested in maintaining brew's official formula or cask?

**Comment by IvanMalison** [comment]
status?

**Comment by skivvies** [comment]
Looks like no one's done this yet:
```
> brew cask search flycut
No Cask found for "flycut".
```

**Comment by IvanMalison** [comment]
How messed up would it be to fork this and make a release to be able to put it on brew?

@TermiT are you there? It would be pretty cool if we could get this on brew...

**Comment by MarkJerde** [comment]
I don't know any thing about cask/brew, but am I correct in understanding that it requires some work in the brew end and nothing more than a pre-compiled binary on the flycut end? If so, why not skip the fork and (if GitHub is your file host of choice) create a new github repository with nothing but the binary? No sense in forking the source unless you intend to extend/maintain it. 

Best of luck,
Mark

**Comment by IvanMalison** [comment]
@MarkJerde thats only true if we go the cask route... I would kind of prefer a formula, but I'd honestly be fine with either.

**Comment by TermiT** [comment]
I'm working on Flycut 2.0, when it's done I will make a cask for it.

**Comment by IvanMalison** [comment]
@TermiT Why wait? I'll volunteer to do all of the brew stuff if we can decide on a canonical source for the current binary...

**Comment by TermiT** [comment]
What do you mean by canonical source?

**Comment by IvanMalison** [comment]
just some location that can be pointed to by the cask. A release in this repository seems like a logical way to do it (as suggested by @filipeximenes)

**Comment by IvanMalison** [comment]
bump... can we please do this. It should be really easy.

**Comment by tomwhoiscontrary** [comment]
The most recent packaged release is linked to from a comment on issue #9:

https://github.com/downloads/TermiT/Flycut/flycut1.5.pkg

**Comment by vitorgalvao** [comment]
There is now [a cask for flycut](https://github.com/caskroom/homebrew-cask/commit/20337280105b1402b0eeea398498e031cd08978d), contributred by @brycethornton.

**Comment by rngtng** [comment]
I confirm there is a cask, issue can be closed.

**Comment by techieshark** [comment]
Confirming that running `brew cask install flycut` installs the app.
