### ISSUE TITLE
Feature: Find (grep) through the history

### ISSUE THREAD

**Issue by a-b** [TermiT/Flycut#4]
Hello again,

another feature I'd like to have easy find in history. 

Scenario: as user I pressed hotkey so I can see window with previous clipped text, I started typing text pattern and now I can scroll by arrow key just through the clips that contains typed pattern.

Thanks again for amazing tool!

**Comment by TermiT** [comment]
There is a search feature in 1.8: https://github.com/TermiT/Flycut/releases
