### ISSUE TITLE
Other issue with pasting (Flycut sending cmd-v)

### ISSUE THREAD

**Issue by okingfisher** [TermiT/Flycut#53]
I am using a Dvorak keyboard, where the V key is mapped to K. Oddly, Flycut seems not be aware of the keymap, and therefore sends cmd-K instead of cmd-V. It does not paste, but instead it performs the cmd-K action, depending on the application.
Jumpcut seemed to work otherwise, it worked independently from the keymap.
What do you think of implementing Jumpcut strategy for pasting? Maybe it was less efficient?
Greetings!

**Comment by nartcan** [comment]
I encountered the same problem while using 'F Turkish' keyboard which remaps 'v' with 'c'.
