### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by sacerdos82** [TermiT/Flycut#54]
The settings of the app reset to default after any restart.

**Comment by elferink** [comment]
This is still an issue, any idea when this will get fixed?

**Comment by MarkJerde** [comment]
This doesn't make any sense. Settings work fine for most folks. Can you elaborate on what you are experiencing? What steps would one take to demonstrate the problem? Where did you get FlyCut from? Did you build it yourself, get it from someone who may have modified it, download that old App Store version? What is unique about your setup that makes it different from a brand new Mac straight from Apple with only your administrator account? Any corporate or institutional software on there? Are you trying to sync FlyCut over DropBox?

Thanks,
Mark

**Comment by elferink** [comment]
Thank you for replying, I didn't know the Apple Store version was outdated.
Especially because this repo links to it.
The links to the website also seem to be broken and I don't see any releases on github.
Where can I get the current version?

**Comment by TermiT** [comment]
https://github.com/TermiT/Flycut/releases
