### ISSUE TITLE
Feature - Favorites line

### ISSUE THREAD

**Issue by klamep** [TermiT/Flycut#55]
Is it possible to make a constant line in menu? Can be named as FAVORITE. User can put their own information to FAVORITE line in preference. 
What do u think?

P.S.
I tired to copy every time my password from text file. (in this case safety is not important for me)

**Comment by nathanbeach** [comment]
Yes, I would love this feature... came here to see if anyone else had suggested it.  I need to paste this one obnoxious junk password over and over again all day logging in and out of test servers.  Having a "favorite" item would be great...

Note to klamep: I actually am using the Evernote menu bar to do sort of this, but it's a little more clumsy (you still have to highlight, copy, and then paste) than the way Flycut could do it.

**Comment by MarkJerde** [comment]
@nathanbeach - Did you know about the Favorites list in Flycut? It's not exactly what klamep requested, but it's where I keep my favorites. Just open the bezel and press "F" to save to the favorites or "f" to switch between the regular list and the favorites list. It's not in the App Store version, of course, since that is 5+ years out of date.

**Comment by nathanbeach** [comment]
@MarkJerde thanks for the tip.  I think I must have the app store version.  I'll figure out how to switch.  I cloned the project and starting looking around just out of interest...

**Comment by MarkJerde** [comment]
@nathanbeach - There's a download link in the readme here: https://github.com/TermiT/Flycut/blob/master/readme.md

**Comment by nathanbeach** [comment]
Wow, okay, that was easy...  thanks!

**Comment by iKorich** [comment]
I need that feature too

can you add option to pin some items in list (add to favorites)
and case to add shortcut to it?
