### ISSUE TITLE
Provide an alternative to App Store

### ISSUE THREAD

**Issue by MoOx** [TermiT/Flycut#56]
I'm using `brew cask` to install softwares (& to automate things) & I would like to create a recipe for that, but I will need a url to get the .app.
Could you use [github releases](https://github.com/TermiT/Flycut/releases) to provide .app directly ?

**Comment by IvanMalison** [comment]
Bump... Any chance of this happening?

**Comment by tomwhoiscontrary** [comment]
This sound like a duplicate of #38 (which is also still open). Maybe this issue should be merged with that one, or closed as a dupe?

**Comment by TermiT** [comment]
https://github.com/TermiT/Flycut/releases
