### ISSUE TITLE
[Wishlist] Log file for keeping a record of clipboard after limit has been reached

### ISSUE THREAD

**Issue by lukebranch** [TermiT/Flycut#63]
Awesome software, I use Flycut on my mac every day, it's a lifesaver. I tend to use the clipboard history quite heavily while developing websites and have always though that Flycut would benefit from some kind of plain text log or similar showing clipboard history with date/time stamps.

A log could be automatically cleared on a specified schedule and it would save trying to track down clipboard items that might have been buried due to the remember limit.

**Comment by MarkJerde** [comment]
This is a late response, but I just came across this old issue.  A feature was added in summer 2015 to automatically save forgotten clippings to individual files.  Nothing to automatically clear them, but it might meet the needs of anyone interested in this issue.

**Comment by salehrastani** [comment]
@MarkJerde i really need to gain access to a an individual clipping that is no longer in my display list. Its about 80 clippings back. Is there a file that I can cat to see the full list of clippings from the past few weeks or days that dont show up in the display?

**Comment by MarkJerde** [comment]
Hi @salehrastani 
Unless you have enabled the "automatically save forgotten clippings" feature, there is no retention of clippings outside of what is displayed in the software.  If you have the feature enabled (which you would see as a checked checkbox in your preferences) the forgotten clippings are saved to individual files on the Desktop, each with the timestamp of forgetting in the file name.
- Mark
