### ISSUE TITLE
Update to newest version in App Store

### ISSUE THREAD

**Issue by psjay** [TermiT/Flycut#69]
I found that the 'app store version' doesn't provide the 'Move pasted item to top of stack' feature, but the application built from source code does.

**Comment by JonJonny** [comment]
OK
so when I click on the "Flycut" link I see all the files
I don't know how to download the full latest version

Sorry for the stupid question

I tried all of the clipboard software and apps, even paid for some but Flycut is the best and it is FREE

We love free baby.......!
Know that I greatly appreciate and help you can provide

**Comment by TermiT** [comment]
Updated
