### ISSUE TITLE
Suggestion: click the icon in menu bar/hotkey to disable flycut

### ISSUE THREAD

**Issue by vrillusions** [TermiT/Flycut#72]
Lets see if I can do this in proper user story format...

* As an end user, I want to click on the icon in menu bar so that I can use the clipboard with history not being saved.
* As an end user, I want to setup and use a hotkey so that I can use the clipboard with history not being saved.

Basically there are times when I'm copying passwords around a lot.  Current solution is to just close app and reopen it afterwards but I'd like to just click on it and then the icon is greyed out or something to indicate it's not working.  For example the Caffeine app.  You can enable or disable it just by clicking on the icon and then you can tell if the cup is full or not on the current state.

Similar in purpose to #64, #22

**Comment by MarkJerde** [comment]
That's a neat idea, Todd. I misunderstood at first and thought you wanted to do an action to prevent storing after you had already copied, but then understood in your secondary explanation. It's not necessarily as easy as what you described would be, but from the bezel view you can press backspace or delete to remove what you are currently looking at from the history. I realize this would require the password to be displayed plaintext, so not good in public, but perhaps this is a trick that can help get you by until someone implements the feature you described. 

Another alternative is my fork of FlyCut which has an option to not save any copy containing at least one each of Upper, Lower, Number, and Symbol, without spaces, of a length exactly matching one of several user-specified lengths. 

Best of luck!
Mark

**Comment by MarkJerde** [comment]
Lucky enough, I was already working on a fix for a change I've been using and needed a visual indicator. So I implemented what you asked for with a visual status indication in the menu bar that would work for my feature as well. I'll hopefully send TermiT a pull request in a few days. Also added the black icon option some have asked for since it was related. 
- Mark
