### ISSUE TITLE
Not available in the Brazilian app store

### ISSUE THREAD

**Issue by santagada** [TermiT/Flycut#79]
The app is not available in the Brazillian app store, I compiled it from source but would be great to have it there.

**Comment by TermiT** [comment]
I will come back to AppStore soon

On Tue, Aug 4, 2015 at 11:23 AM, Leonardo Santagada <
notifications@github.com> wrote:

> The app is not available in the Brazillian app store, I compiled it from
> source but would be great to have it there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TermiT/Flycut/issues/79>.
>



-- 
Sincerely,
Gennadiy Potapov

**Comment by TermiT** [comment]
Should be available now
