### ISSUE TITLE
How do I compile the latest code?

### ISSUE THREAD

**Issue by komandur** [TermiT/Flycut#81]
Hi, 

I've been an avid user of Flycut (1.5) with one annoying nit .... it always picks the very first item in my list, even if I select any other item.
1. Do I have some config wrong that explains the above behavior ?
2. Is this fixed in the later code updates ?  
3. I cloned from git, but there is no makefile/ ./configure or anything. What are the compile instructions. Can somebody upload pkg for the latest code ?

**Comment by MarkJerde** [comment]
Hi komandur.
You will need Xcode to build Flycut.  You can get it for free from the App Store.  Once you have that installed, just open the Flycut.xcodeproj in your clone and hit the play button.  If you want to run it outside of Xcode, the easiest way is to select Archive from the Project menu in Xcode, then click Export.

If you don't want to install Xcode, I provided a build recently in #75.  https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-FavoritesBeta.zip

Best of luck,
Mark

**Comment by gsilos** [comment]
Hello MarkJerde,

I tried to open the Flycut.xcodeproj and run by pressing the play button, but it says: "Signing for "Flycut" requires a development team. Select a development team in the build settings editor that matches the selected profile "3abf5364-dfb4-4792-a5a0-377a74572bcb"."

Do you know what does it means?

**Comment by gsilos** [comment]
I tried to create the Export but no clue on why the button is disabled for me. :(
<img width="1437" alt="screen shot 2018-05-12 at 18 39 42" src="https://user-images.githubusercontent.com/7491155/39959589-faf75636-5613-11e8-9a5e-4b0056f20811.png">

**Comment by MarkJerde** [comment]
Hi @gsilos - I'd guess it has something to do with the "Distribution requires enrollment in the Apple Developer Program" text below the "Export" button.  I believe enrollment is free if you are not distributing via the App Store.

Hope this helps,
Mark

**Comment by gsilos** [comment]
it costs 99€ to enroll myself in the Apple Developer Program as an individual that will not distribute via App Store. :(

**Comment by gsilos** [comment]
And this Apple's answer for my question of why this is not working for my account:

<img width="995" alt="screen shot 2018-05-15 at 18 38 09" src="https://user-images.githubusercontent.com/7491155/40070763-489b3efe-586f-11e8-8ad1-e9006b7c3fdb.png">

Thank you anyway! I will Try to see another way.

**Comment by MarkJerde** [comment]
Either they are wrong or they treat Germans different.  I just created a new user, cloned the repository, opened the project, disabled signing, did a build, archive, export, and ran the exported app.  I can show pictures to prove it if you think they'd help.  Make sure you are disabling signing via the Build Settings tab of the project.  https://stackoverflow.com/questions/35589272/xcode-export-mac-app-without-developer-program

Post back if you are still having trouble.  You should be allowed to export an app from Xcode.

Hope this helps,
Mark
