### ISSUE TITLE
broken in el capitan dp7 (and previous)

### ISSUE THREAD

**Issue by alokdhir** [TermiT/Flycut#83]
big delay between pressing hotkey and clips showing up to choose from.

**Comment by MarkJerde** [comment]
Thanks for the report, alokhdir.  What build of Flycut are you using?  App Store, self-built, or downloaded from somewhere else?  If self-built, it's up to date, right?
This sounds concerning and I'll probably setup El Cap on an external drive just to figure it out once El Cap is officially released.  Not to blow it off at all.  I just don't have time to deal with DPs at this point and wanted you to know that it's on somebody's radar.
Thanks again,
Mark

**Comment by alokdhir** [comment]
Yes - fully up to date self built. 

Thanks

**Comment by jimbrechts** [comment]
Hi, I have the same issue.

I'm using flycut 1.5 downloaded from the Mac App Store.
OS X El Capitan v10.11

On a MB Air 13" from 2014.

Anybody have an idea about a fix?

**Comment by michaelcurry** [comment]
Did you try **un**checking the setting `animate bezel appearance`

![image](https://cloud.githubusercontent.com/assets/2658933/10489059/6014003c-7250-11e5-842e-79b491f5f8e8.png)

**Comment by michaelcurry** [comment]
Strangely enough,  I have had this issue on one of my laptops but not the other.  See #89 

I have had this happen most recently on this machine.  I am going to re-archive the package and put a stop by step list of what I have done to so this.  Maybe that will uncover some more details. for @MarkJerde  to look at :+1:

**Comment by michaelcurry** [comment]
- download Zip (Master) From gitHub

- Open `Flycut.xcodeproj` in xCode 7.1.1

- Update Recommended Settings

![image](https://cloud.githubusercontent.com/assets/2658933/11384393/3253e13c-92c4-11e5-8ac1-fdad95c758e3.png)

- Product > Archive

Causes These Warning: 
![image](https://cloud.githubusercontent.com/assets/2658933/11384410/525bae1a-92c4-11e5-827c-7b0dc1e62ad3.png)

- Export As Mac Application

- Run Application

- Copy Something

- Shift+Cmd+V to select entry

- Enter

- nothing pastes

YUP!  Still an issue ... did I do anything wrong here @MarkJerde ?

**Comment by MarkJerde** [comment]
@michaelcurry  Hi Michael,
I just figured something out on this "enter not pasting" issue.  I saw the same problem while doing some recent development, and it turns out I had followed the same process you described above of accepting the recommended settings.  Previously I had been selecting "Don't Code Sign" for Code Signing Identity in the project Code Signing settings.

It looks like the recommended settings do some sort of sandboxing or such, as they put the save file in Library/Containers/com.generalarcade.flycut/Data/Library/Application Support/Flycut/com.generalarcade.flycut.plist vs the Library/Application Support/Flycut/com.generalarcade.flycut.plist location used with my approach.

I'll have to debug more sometime, but for now I would suggest the "Don't Code Sign" approach.

- Mark

**Comment by michaelcurry** [comment]
@MarkJerde As this is am amazing application, why don't you sign this and put it on the app store (seems that there is an old version of this)

If you want someone to put it on the app store for you, I can put it up there and keep it up-to-date (re-publish with fixes) every few weeks / or every month.  

Let me know.

--mike

**Comment by TermiT** [comment]
@michaelcurry We'll put an update when it's ready, no need to make clones in AppStore

**Comment by MarkJerde** [comment]
I confirmed on El Cap that the bezel appearance is slow when animated, and also that the bezel animation sucks in awful ways on a Retina display on Yosemite.  On the latter it appeared to be confused as to the screens dimensions and jumped from huge to normal.  Worked fine on the two non-Retina external displays.  Didn't think to try external displays with El Cap to see if that makes a difference.  I'll include a patch that changes the default to not animate on 10.10+.

I agree that it is better not to have multiple Flycuts in the app store (if they even allow that), and as long as TermiT wants to keep his one in there I won't worry about it.

- Mark

**Comment by michaelcurry** [comment]
:+1: sounds good.
