### ISSUE TITLE
Suggestion: paste all clips

### ISSUE THREAD

**Issue by douglsmith** [TermiT/Flycut#84]
I tend to do work where I copy this and that and that other thing and then paste them all into the same document. It would be really useful to have a way to paste all clips that have been copied. I don't care if there's extra stuff. It's faster to clean that up than to paste each individual item.

**Comment by MarkJerde** [comment]
Hi Doug,
Selecting "Merge All" from the Flycut menu and then pasting would accomplish this.  Is there any reason that option isn't suitable for you?

Best wishes,
Mark

**Comment by douglsmith** [comment]
That's perfect. I just hadn't realized it was there since I had been using the Apple Store version.

Thanks for the pointer.
