### ISSUE TITLE
Favorite store is not working for v1.5

### ISSUE THREAD

**Issue by HappyRay** [TermiT/Flycut#88]
The favorite store feature sounds very useful. But it doesn't work for me. I have v1.5.

https://github.com/TermiT/Flycut/blob/master/help.md

"f: Switch between the main clipboard history store and the favorites store. The favorites store appears in the Bezel and works in the same way as the main clipboard history store, aside from having a yellow tint to the Bezel.

F: Save the clipboard history item currently displayed to the favorites store, deleting it from the main clipboard history store and closing the Bezel.
"

**Comment by MarkJerde** [comment]
I may be mistaken, but it looks like 1.5 is a rather old build.  The source in GitHub seems to still have the version number set to 1.0, but includes all of the features I have seen mentioned as "new in 1.5" (per http://www.macupdate.com/app/mac/42134/flycut).  It appears that the version number change was never pushed to GitHub.  Nobody ever does update the version number, so it's not useful for identifying what you are running compared to describing where and when it was downloaded or built from.

The favorite store feature was just added 25 days ago.  Here's a build that contains it.  I'm pretty sure that this build matches the current latest code.  https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-2015.09.08.zip?raw=true

Hopefully this solves your problem.
Mark

**Comment by HappyRay** [comment]
Thanks Mark.

I downloaded flycut from the Apple app store. I will try the more recent build when I get a chance.

**Comment by HappyRay** [comment]
@MarkJerde 

I tried your build. But my computer's security policy only allows running apps from app store. Thanks anyway though.

Does anyone know when a new version will be published to the app store?

**Comment by MarkJerde** [comment]
@HappyRay 
I won't make any assumptions about your computer, but the default OS X install will decline to run unsigned apps (the first time) if you double-click the icon.  The default OS X install also allows you to bypass this by doing a control-click on the icon and selecting "Open".  This may help you to run my build.

But if your computer was configured by some IT department then you may be stuck.  The App Store version has only been updated once, and that was back in 2011, just so you know.  Off course, that doesn't mean it won't ever be updated again.

Best of luck,
Mark

**Comment by HappyRay** [comment]
Mark,

Your suggestion worked. I should have researched myself how to bypass this security check. I assumed that the restriction was placed by our IT group.

I failed to build the project myself because of some compiler warnings though. But I don't have to compile at this time.

Thanks!
