### ISSUE TITLE
Ran Flycut code in XCode 7 with errors...

### ISSUE THREAD

**Issue by sim4life** [TermiT/Flycut#90]
I managed to successfully build the project in XCode 7.0.1 in Yosemite but running it gives the following error:
`objc[52648]: Class DBUserDefaultsController is implemented in both /Users/myname/Library/Developer/Xcode/DerivedData/Flycut-bljqhsxjbkajodceioehaihcsqek/Build/Products/Debug/Flycut.app/Contents/Frameworks/DBUserDefaults.framework/Versions/A/DBUserDefaults and /Users/myname/Library/Developer/Xcode/DerivedData/Flycut-bljqhsxjbkajodceioehaihcsqek/Build/Products/Debug/Flycut.app/Contents/MacOS/Flycut. One of the two will be used. Which one is undefined.`
`2015-10-19 17:23:01.776 Flycut[52648:687910] code: 9, flags: 1179648`
`2015-10-19 17:23:01.910 Flycut[52648:687910] Not array`
`2015-10-19 17:23:02.166 Flycut[52648:687955] Couldn't list login items error -600`

The app is loaded in the top menu bar but I think these errors fatal. Any solutions?

**Comment by MarkJerde** [comment]
It works though, right? You get the Flycut icon in the menu bar and Shift-Cmd-V opens the bezel (though it may be slow on Yo)? The duplicate warning has been there for ages. The login items message may prevent "launch on startup". Just want to help you use it despite needing improvement on Yo and those look like non-fatal messages.

Best of luck,
Mark

**Comment by sim4life** [comment]
Yes, sorry @MarkJerde I edited my original post before reading your response.
The Flycut app is working but I'd like to fix those errors. Any references in the code?
