### ISSUE TITLE
Dropbox syncing issue on machine with two Dropox accounts

### ISSUE THREAD

**Issue by justin-r-r** [TermiT/Flycut#92]
I've got Dropbox for business, which allows 'work' and 'home' Dropbox accounts to run on the same machine. Each has a separate Dropbox folder in the user directory.

I want Flycut syncing to happen via my 'home' Dropbox account, but Flycut automatically placed its plist file in my 'work' Dropbox folder, and there appears to be no way to tell it to put it in my 'home' Dropbox folder.

**Comment by TermiT** [comment]
I've removed Dropbox support
