### ISSUE TITLE
Display source App of clipping and time that it was copied

### ISSUE THREAD

**Issue by MarkJerde** [TermiT/Flycut#94]
I couldn't find an existing request for this, and thought it might be a good idea, so I added code that will show the icon for the App the clipping came from, the name of that App, and the time at which the clipping was made.  I expect some will not want this, so I'll be adding a checkbox to the Appearance panel in the preferences to disable it.  Any feedback is much appreciated.

Beta download: https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-AppAndTimestampBeta.zip?raw=true

Cool features:
* Fully compatible to and from versions of Flycut before this feature, so nothing gets clunky.
* Automatically hides the new Bezel fields if they are empty.

Screenshot:
![screen shot 2016-01-18 at 9 04 25 pm](https://cloud.githubusercontent.com/assets/903956/12409951/4d8d5428-be35-11e5-8e34-7b969f9292cf.png)

Thanks!
Mark

**Comment by TermiT** [comment]
Nice, I like source app feature!

**Comment by MarkJerde** [comment]
I just pushed an update to the beta app.  It now has a control in the Appearance preferences panel.  

Related to this, I gutted that page of the preferences and switched it to programmatic creation.  It should look and work identical.  Programmatic preferences panels have been on my to-do list for a while, since the generated binary nib file is a significant cause of merge conflicts and has prevented integration of Flycut patches from less-experienced developers in the past.  There shouldn't be any bugs in that conversion, but if any are found please let me know.

Thanks,
Mark

**Comment by MarkJerde** [comment]
## Summary
A final beta has been posted to https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-AppAndTimestampBeta.zip?raw=true
The code has been pushed to https://github.com/MarkJerde/Flycut/tree/ClippingSource_Fixes_Features_Versions
A merge request will be submitted in a few days (to give time for any comments or bug reports).

## Content
### Bug fix - OS X 10.10 Yosemite treatment of menu-bar icon
OS X 10.10 Yosemite got a bit too crafty and would apply it's own "disabled" styling if the NSStatusItem image is an image that has "disabled" in its name. Changed to xout to keep it looking colorful.
### Avoid bezel animation problems on 10.10+ (#83)
Bezel animation has demonstrated problems on 10.10 Retina and any 10.11 setup. Until the problems are solved, default to not animate on installs where it would be problematic.
### Display clipping source app and copy time in the bezel
![screen shot 2016-01-18 at 9 04 25 pm](https://cloud.githubusercontent.com/assets/903956/12541425/8e470828-c2dc-11e5-895e-c1fc9ecad38c.png)
### Programmatic population of Preferences panel for Appearance
Previously, any change the the preferences or most other GUI elements would cause binary file English.lproj/MainMenu.nib/keyedobjects.nib to be modified.  With no way to three-way-merge a binary file, this made multi-person development difficult and caused GUI changes to have to be redone until they were merged with the master.  One example of where this binary nib has caused problems for Flycut is #58.  This conversion has currently just been made for the Appearance panel, with the others being a to-do for the future.  The panel still looks the same after this change, aside from slider bars no longer being a few pixels off alignment and inconsistent in spacing.
### Version bump and automatic build numbering.
Bumped Flycut up to 1.7 since a lot has been done since the App Store version 1.5.  In response to the difficulty in providing support without knowing where someone's Flycut build came from, and if it is out of date or customized, a hook was added to the build to set the build number shown in the "About Flycut" panel to include the git hash built from.  Also included are the number of local and remote changes, the local hash (if there are local committed changes), the number of local uncommitted lines changed, and the year and month of the build.  None of this is personally identifying, but the hash can quickly connect any report to the exact GitHub code it came from.

Example of unmodified code fresh cloned from GitHub: ![screen shot 2016-01-24 at 2 34 43 pm](https://cloud.githubusercontent.com/assets/903956/12541605/e0d5e62a-c2de-11e5-93fc-1167c4e993e0.png)
One line removed, one line added.  (Two total lines.): ![screen shot 2016-01-24 at 2 35 26 pm](https://cloud.githubusercontent.com/assets/903956/12541626/0d9f5682-c2df-11e5-9deb-bbaae639237e.png)
One commit added: 
![screen shot 2016-01-24 at 2 35 55 pm](https://cloud.githubusercontent.com/assets/903956/12541643/3855c492-c2df-11e5-8faa-5cbba4763b9b.png)
One commit added and three lines of additional changes:
 ![screen shot 2016-01-24 at 2 38 09 pm](https://cloud.githubusercontent.com/assets/903956/12541649/4ae59d1c-c2df-11e5-8bcd-3ae173f5152b.png)
Based on one remote version but there have been five local and six remote changes ("6.5" in the string) since then: 
![screen shot 2016-01-24 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/903956/12541661/5f5ed704-c2df-11e5-91ea-fc60b6ee3e4d.png)

I'll submit the merge request in a few days.
