### ISSUE TITLE
Search box not always working

### ISSUE THREAD

**Issue by Bicet** [TermiT/Flycut#95]
How to reproduce the issue.
Open flycut menu, the search box is working.
click on desktop
Open flycut menu, the search box is NOT working.

EL Cap 10.11.2

**Comment by MarkJerde** [comment]
Verified.  It seems pretty random when it actually does work, but quite often does not work.  Pretty annoying to use.  ;-)

I'll have to do some debugging once I get a development system up to El Cap.  Just used El Cap for the first time ever today, in a test to see if I could deal with the new "rootless" model.  I'll double check that this isn't also a problem on Yosemite.

Thanks again,
Mark

**Comment by Bicet** [comment]
Thank you Mark!

**Comment by fiddlerwoaroof** [comment]
For me, it works when the bezel or preferences window is active but not otherwise.
