### ISSUE TITLE
Update App store version

### ISSUE THREAD

**Issue by knyttl** [TermiT/Flycut#97]
Last updated: 2011. It would be nice to be able to install current version.

**Comment by michaelcurry** [comment]
:+1: to this request.  I have yet to successfully build this application without using a sign.

**Comment by serkanyersen** [comment]
Is there a place to download the latest version if it's not going to be on app store?

**Comment by TermiT** [comment]
I plan to release an update next week.

**Comment by TermiT** [comment]
I have bad news, guys. Apple forbid to use `CGEventPost` call for sandboxed apps. And this part is very import as we use `CGEventPost` to emulate Command+V shortcut. I'll try to find a workaround, but probably I will not be able to update App Store version.

**Comment by knyttl** [comment]
I tried to update to 1.8 just by downloading and now FlyCut will not even run. Is there some kind of crash log?

**Comment by TermiT** [comment]
I've uploaded the new zip archive, please try again.

**Comment by knyttl** [comment]
Good, thanks.

**Comment by serkanyersen** [comment]
@TermiT Thanks for this, it was a really needed update.

**Comment by wifiprintguy** [comment]
Apple App Store: v1.5
GitHub: v1.8
